blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/mironovsergey/bootstrap-sheet#readme
    about: Read the full documentation
  - name: Discussions
    url: https://github.com/mironovsergey/bootstrap-sheet/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Vulnerability
    url: https://github.com/mironovsergey/bootstrap-sheet/security/policy
    about: Please report security vulnerabilities privately via email
