name: Greetings

on: [pull_request_target, issues]

permissions:
  issues: write
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
      - name: Greet first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Thanks for opening your first issue! We appreciate you taking the time to contribute to Bootstrap Sheet.

            A maintainer will review your issue soon. In the meantime, please make sure you've provided all the necessary information, including:
            - A clear description of the issue
            - Steps to reproduce (if applicable)
            - Your environment details

            If you'd like to work on this issue yourself, feel free to open a pull request!
          pr-message: |
            🎉 Thanks for opening your first pull request! We're excited to review your contribution to Bootstrap Sheet.

            Please make sure:
            - [ ] Your code follows our [contribution guidelines](https://github.com/mironovsergey/bootstrap-sheet/blob/main/CONTRIBUTING.md)
            - [ ] All tests pass (`npm test`)
            - [ ] Your code is properly formatted (`npm run format`)
            - [ ] You've updated documentation if needed

            A maintainer will review your PR as soon as possible. Feel free to ask questions if you need help!
