name: Mark Stale Issues and PRs

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          # Issues
          days-before-issue-stale: 60
          days-before-issue-close: 14
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,bug,enhancement'
          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity.
            It will be closed in 14 days if no further activity occurs.
            Thank you for your contributions.
          close-issue-message: |
            This issue was automatically closed because it has been stale for 14 days with no activity.
            If you believe this issue is still relevant, please reopen it with additional context.

          # Pull Requests
          days-before-pr-stale: 30
          days-before-pr-close: 14
          stale-pr-label: 'stale'
          exempt-pr-labels: 'pinned,security,work-in-progress'
          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity.
            It will be closed in 14 days if no further activity occurs.
            Thank you for your contributions.
          close-pr-message: |
            This pull request was automatically closed because it has been stale for 14 days with no activity.
            If you would like to continue working on this, please reopen it and provide an update.

          # General settings
          operations-per-run: 100
          remove-stale-when-updated: true
          ascending: true
